In [ ]:
import tensorflow as tf

In [ ]:
## Inputs binary vectors
X = tf.constant([[0, 0], [0, 1], [1, 0], [1, 1]])
## Input weights
W = tf.constant([[1, 1], [1, 1]])
## Output weights
theta = tf.constant([[1, -2]])
## input bias
c = tf.constant([[0, -1]])
print(X)

tf.Tensor(
[[0 0]
 [0 1]
 [1 0]
 [1 1]], shape=(4, 2), dtype=int32)


In [ ]:
## Compute hidden layer without the activation
h_no_activation = tf.matmul(X, W) + c
print("Hidden layer without activation")
print(h_no_activation)

tf.Tensor(
[[ 0 -1]
 [ 1  0]
 [ 1  0]
 [ 2  1]], shape=(4, 2), dtype=int32)


In [ ]:
## See the outputs without an activation
Y = tf.matmul(h_no_activation, tf.transpose(theta))
print(Y)

tf.Tensor(
[[2]
 [1]
 [1]
 [0]], shape=(4, 1), dtype=int32)


In [ ]:
## Compute outputs with a ReLU activation
h_with_activation = tf.nn.relu(tf.matmul(X, W) + c)
print("Hidden layer with activation")
print(h_with_activation)

tf.Tensor(
[[0 0]
 [1 0]
 [1 0]
 [2 1]], shape=(4, 2), dtype=int32)


In [ ]:
## Compute the correct outputs 
Y = tf.matmul(h_with_activation, tf.transpose(theta))
print(Y)

tf.Tensor(
[[0]
 [1]
 [1]
 [0]], shape=(4, 1), dtype=int32)
